// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using TImeMaster.Helpers;

namespace TImeMaster
{
    [TestFixture]
    public class Tests : TestBase
    {

        [Test]
        public void MainTest()
        {
            var accountData = new AccountData("varene9071@pxjtw.com","55555aa");
            var groupData = new GroupData("Test");
            app.Navigation.OpenHomePage();
            app.Auth.Login(accountData);
            app.Group.AddAction(groupData);
        }
       
    }
}